# Generated by Django 2.0.7 on 2018-07-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField(default=0)),
                ('cusdetail', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
