# Generated by Django 2.0.7 on 2018-07-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('info', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
