# Generated by Django 2.0.7 on 2018-08-05 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20180805_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.Customer'),
        ),
    ]
