# Generated by Django 2.0.7 on 2018-08-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20180805_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
